// infergen generates raylib return-type maps for internal/infer from libs/raylib/raw.dd.
//
//go:generate is wired from internal/infer/infer.go
package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"regexp"
	"sort"
	"strings"
)

var fnLine = regexp.MustCompile(`^\s+fn\s+(\w+)\s*\([^)]*\)\s*(?:->\s*([^;]+))?\s*;`)

func main() {
	rawPath := flag.String("raw", "libs/raylib/raw.dd", "path to raw.dd bindings")
	outPath := flag.String("out", "internal/infer/raylib_returns_gen.go", "output Go file")
	flag.Parse()

	f, err := os.Open(*rawPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "infergen: open %s: %v\n", *rawPath, err)
		os.Exit(1)
	}
	defer f.Close()

	returns := map[string]string{}
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := sc.Text()
		m := fnLine.FindStringSubmatch(line)
		if m == nil {
			continue
		}
		name := m[1]
		if m[2] == "" {
			continue
		}
		returns[name] = normType(strings.TrimSpace(m[2]))
	}
	if err := sc.Err(); err != nil {
		fmt.Fprintf(os.Stderr, "infergen: read %s: %v\n", *rawPath, err)
		os.Exit(1)
	}

	names := make([]string, 0, len(returns))
	for name := range returns {
		names = append(names, name)
	}
	sort.Strings(names)

	var b strings.Builder
	b.WriteString("// Code generated by tools/infergen from libs/raylib/raw.dd. DO NOT EDIT.\n\n")
	b.WriteString("package infer\n\n")
	b.WriteString(fmt.Sprintf("// RaylibReturnCount is the number of raylib functions with inferred return types.\nconst RaylibReturnCount = %d\n\n", len(names)))
	b.WriteString("var raylibReturns = map[string]string{\n")
	for _, name := range names {
		fmt.Fprintf(&b, "\t%q: %q,\n", name, returns[name])
	}
	b.WriteString("}\n")

	if err := os.WriteFile(*outPath, []byte(b.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "infergen: write %s: %v\n", *outPath, err)
		os.Exit(1)
	}
	fmt.Printf("infergen: wrote %d return types to %s\n", len(names), *outPath)
}

func normType(t string) string {
	t = strings.TrimSuffix(t, "?")
	switch t {
	case "Vector2":
		return "Vec2"
	case "Vector3":
		return "Vec3"
	case "Vector4":
		return "Vec4"
	case "Rectangle":
		return "Rect"
	case "Texture2D":
		return "Texture"
	case "RenderTexture2D":
		return "RenderTexture"
	case "cstring":
		return "const char*"
	default:
		return t
	}
}
