package codegen

import (
	"datadream/internal/ast"
)

func (g *Generator) emitHeader(appName string) {
	g.emit("/* Generated by DataDream compiler - App: %s */\n", appName)
	g.emit("/* Do not edit this file manually */\n\n")
	g.emit("#include <stdio.h>\n")
	g.emit("#include <stdlib.h>\n")
	g.emit("#include <string.h>\n")
	g.emit("#include <stdbool.h>\n")
	g.emit("#include <math.h>\n")
	if g.usesRaylib {
		g.emit("#include <raylib.h>\n")
		g.emit("#include <raymath.h>\n")
		g.emit("#include <rlgl.h>\n")
	}
	g.emit("\n")
	g.emit("/* ── DataDream runtime types ── */\n")
	if !g.usesRaylib {
		g.emit("typedef struct { float x, y; } Vec2;\n")
		g.emit("typedef struct { float x, y, z; } Vec3;\n")
		g.emit("typedef struct { float x, y, z, w; } Vec4;\n")
		g.emit("typedef struct { unsigned char r, g, b, a; } Color;\n")
		g.emit("typedef struct { float m[16]; } Mat4;\n")
	} else {
		g.emit("typedef Vector2 Vec2;\n")
		g.emit("typedef Vector3 Vec3;\n")
		g.emit("typedef Vector4 Vec4;\n")
		g.emit("typedef Matrix Mat4;\n")
		g.emit("typedef Rectangle Rect;\n")
		g.emit("typedef Texture2D Texture;\n")
		g.emit("typedef RenderTexture2D RenderTexture;\n")
	}
	g.emit("\n")
	g.emit("typedef struct {\n")
	g.emit("    Vec2 position;\n")
	g.emit("    int size;\n")
	if g.usesRaylib {
		g.emit("    Color color;\n")
	} else {
		g.emit("    Color color;\n")
	}
	g.emit("    void* font;\n")
	g.emit("    float rotation;\n")
	g.emit("    bool shadow;\n")
	g.emit("} TextOptions;\n")
	g.emit("\n")
	if g.usesRaylib {
		g.emit("static void datadream_draw_text(const char* text, TextOptions opts) {\n")
		g.emit("    DrawText(text, (int)opts.position.x, (int)opts.position.y, opts.size, opts.color);\n")
		g.emit("}\n")
	} else {
		g.emit("static void datadream_draw_text(const char* text, TextOptions opts) {\n")
		g.emit("    (void)text; (void)opts; /* runtime stub */\n")
		g.emit("}\n")
	}
	g.emit("\n")
	g.emit("/* ── DataDream runtime helpers ── */\n")
	if !g.usesRaylib {
		g.emit("static inline Vec2 vec2(float x, float y) { return (Vec2){x, y}; }\n")
	} else {
		g.emit("static inline Vec2 vec2(float x, float y) { return (Vec2){x, y}; }\n")
	}
	g.emit("static inline Vec3 vec3(float x, float y, float z) { return (Vec3){x, y, z}; }\n")
	g.emit("static inline Vec4 vec4(float x, float y, float z, float w) { return (Vec4){x, y, z, w}; }\n")
	if !g.usesRaylib {
		g.emit("static inline Color color(unsigned char r, unsigned char g, unsigned char b, unsigned char a) { return (Color){r, g, b, a}; }\n")
	}
	g.emit("static inline float vec2_length(Vec2 v) { return sqrtf(v.x*v.x + v.y*v.y); }\n")
	g.emit("static inline float vec3_length(Vec3 v) { return sqrtf(v.x*v.x + v.y*v.y + v.z*v.z); }\n")
	g.emit("\n")
	g.emit("/* ── DataDream string interpolation helper ── */\n")
	g.emit("static char _datadream_strbuf[4096];\n")
	g.emit("#define datadream_print(...) printf(__VA_ARGS__)\n")
	g.emit("static const char* datadream_cstr(const char* s) { return s; }\n")
	g.emit("\n")
	if g.usesFrameArena {
		g.emitFrameArenaRuntime()
	}
	if g.usesLevelArena {
		g.emitLevelArenaRuntime()
	}
	if g.needsArrayRuntime {
		g.emitArrayRuntime()
	}
	g.emitColorRuntime()
	g.emitGameRuntime()
	g.emitStdlibRuntime()
	g.emitUIRuntime()
	g.emitFriendlyRuntime()
}

func (g *Generator) collectDecls(prog *ast.Program) {
	for _, node := range prog.Stmts {
		switch n := node.(type) {
		case *ast.StructDecl:
			g.structs = append(g.structs, n.Name)
			if g.structMethods == nil {
				g.structMethods = map[string]map[string]bool{}
			}
			methods := map[string]bool{}
			for _, m := range n.Methods {
				methods[m.Name] = true
			}
			g.structMethods[n.Name] = methods
		case *ast.EntityDecl:
			g.entities = append(g.entities, n.Name)
			if g.hasAttr(n.Attrs, "packed") {
				if g.packedEntities == nil {
					g.packedEntities = map[string]bool{}
				}
				g.packedEntities[n.Name] = true
			}
			if g.entityFields == nil {
				g.entityFields = map[string]map[string]string{}
			}
			if g.entityMethods == nil {
				g.entityMethods = map[string]map[string]bool{}
			}
			methods := map[string]bool{}
			for _, m := range n.Methods {
				methods[m.Name] = true
			}
			g.entityMethods[n.Name] = methods
			fields := map[string]string{
				"position": "Vec3",
				"velocity": "Vec3",
				"active":   "bool",
			}
			for _, f := range n.Fields {
				t := "float"
				if f.Type != nil {
					t = g.typeToC(f.Type)
				}
				fields[f.Name] = t
			}
			g.entityFields[n.Name] = fields
		case *ast.EnumDecl:
			if g.enums == nil {
				g.enums = map[string]map[string]bool{}
			}
			variants := map[string]bool{}
			for _, v := range n.Variants {
				variants[v] = true
			}
			g.enums[n.Name] = variants
		}
	}
}

func (g *Generator) emitMain(prog *ast.Program) {
	g.emit("\n/* ── Entry point ── */\n")
	g.emit("int main(int argc, char** argv) {\n")
	g.indent++
	// Call scene init and start functions
	for _, node := range prog.Stmts {
		switch n := node.(type) {
		case *ast.SceneDecl:
			g.iemit("scene_%s_init();\n", n.Name)
			if n.HasStart {
				g.iemit("scene_%s_start();\n", n.Name)
			}
		case *ast.LifecycleBlock:
			if n.Name == "start" {
				g.iemit("lifecycle_start();\n")
			}
		}
	}
	g.iemit("return 0;\n")
	g.indent--
	g.emit("}\n")
}
