// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Build(arg1, arg2, arg3) {
  return window['go']['main']['App']['Build'](arg1, arg2, arg3);
}

export function Check(arg1, arg2) {
  return window['go']['main']['App']['Check'](arg1, arg2);
}

export function Doctor() {
  return window['go']['main']['App']['Doctor']();
}

export function IsDesktop() {
  return window['go']['main']['App']['IsDesktop']();
}

export function NewFile(arg1, arg2) {
  return window['go']['main']['App']['NewFile'](arg1, arg2);
}

export function OpenProject() {
  return window['go']['main']['App']['OpenProject']();
}

export function Read(arg1) {
  return window['go']['main']['App']['Read'](arg1);
}

export function Run(arg1, arg2) {
  return window['go']['main']['App']['Run'](arg1, arg2);
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}

export function SetProjectRoot(arg1) {
  return window['go']['main']['App']['SetProjectRoot'](arg1);
}

export function Tree(arg1) {
  return window['go']['main']['App']['Tree'](arg1);
}

export function Version() {
  return window['go']['main']['App']['Version']();
}

export function Write(arg1, arg2) {
  return window['go']['main']['App']['Write'](arg1, arg2);
}
