// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ide} from '../models';

export function Build(arg1:string,arg2:string,arg3:boolean):Promise<ide.CommandResult>;

export function Check(arg1:string,arg2:string):Promise<ide.CheckResult>;

export function Doctor():Promise<ide.DoctorStatus>;

export function IsDesktop():Promise<boolean>;

export function NewFile(arg1:string,arg2:string):Promise<ide.FileContent>;

export function OpenProject():Promise<ide.VersionInfo>;

export function Read(arg1:string):Promise<ide.FileContent>;

export function Run(arg1:string,arg2:string):Promise<ide.CommandResult>;

export function Search(arg1:string):Promise<ide.SearchResult>;

export function SetProjectRoot(arg1:string):Promise<ide.VersionInfo>;

export function Tree(arg1:string):Promise<ide.TreeNode>;

export function Version():Promise<ide.VersionInfo>;

export function Write(arg1:string,arg2:string):Promise<void>;
