package bindgen

import (
	"fmt"
	"path/filepath"
	"strings"
)

// ─── Markdown documentation generator ────────────────────────────────────────

type DocGenerator struct {
	result  *ParseResult
	libName string
}

func NewDocGenerator(result *ParseResult) *DocGenerator {
	return &DocGenerator{result: result, libName: result.LibName}
}

func (g *DocGenerator) GenerateMarkdown() string {
	var sb strings.Builder
	libTitle := capitalize(g.libName)

	sb.WriteString(fmt.Sprintf("# %s — DataDream Bindings\n\n", libTitle))
	sb.WriteString(fmt.Sprintf("Auto-generated DataDream bindings for the `%s` C library.\n\n", g.libName))
	sb.WriteString(fmt.Sprintf("**Source header:** `%s`\n\n", filepath.Base(g.result.HeaderFile)))
	sb.WriteString("---\n\n")

	// Table of contents
	sb.WriteString("## Contents\n\n")
	if len(g.result.Types) > 0 {
		sb.WriteString("- [Types](#types)\n")
	}
	if len(g.result.Defines) > 0 {
		sb.WriteString("- [Constants](#constants)\n")
	}
	sb.WriteString("- [Functions](#functions)\n")
	sb.WriteString("\n---\n\n")

	// Types
	if len(g.result.Types) > 0 {
		sb.WriteString("## Types\n\n")
		for _, t := range g.result.Types {
			if t.Comment != "" {
				sb.WriteString(fmt.Sprintf("### `%s`\n\n%s\n\n", t.Name, t.Comment))
			} else {
				sb.WriteString(fmt.Sprintf("### `%s`\n\n", t.Name))
			}
			switch t.Kind {
			case "struct":
				sb.WriteString("```dd\nstruct " + t.Name + " {\n")
				for _, f := range t.Fields {
					sb.WriteString(fmt.Sprintf("    %s: %s;\n", f.Name, cTypeToDataDream(f.Type.Raw)))
				}
				sb.WriteString("}\n```\n\n")
			case "enum":
				sb.WriteString("```dd\nenum " + t.Name + " {\n")
				for _, v := range t.Values {
					name := stripEnumPrefix(v.Name, t.Name)
					if v.Value != "" {
						sb.WriteString(fmt.Sprintf("    %s; // %s\n", name, v.Value))
					} else {
						sb.WriteString(fmt.Sprintf("    %s;\n", name))
					}
				}
				sb.WriteString("}\n```\n\n")
			}
		}
	}

	// Constants
	if len(g.result.Defines) > 0 {
		sb.WriteString("## Constants\n\n")
		sb.WriteString("| Name | Value |\n|------|-------|\n")
		for _, d := range g.result.Defines {
			val := strings.TrimSpace(d.Value)
			if strings.Contains(val, "(") && !strings.HasPrefix(val, "(") {
				continue
			}
			sb.WriteString(fmt.Sprintf("| `%s` | `%s` |\n", d.Name, val))
		}
		sb.WriteString("\n")
	}

	// Functions by group
	sb.WriteString("## Functions\n\n")
	groups := map[string][]CFunc{}
	var groupOrder []string
	for _, fn := range g.result.Funcs {
		if _, exists := groups[fn.Group]; !exists {
			groupOrder = append(groupOrder, fn.Group)
		}
		groups[fn.Group] = append(groups[fn.Group], fn)
	}

	for _, group := range groupOrder {
		fns := groups[group]
		sb.WriteString(fmt.Sprintf("### %s\n\n", group))

		for _, fn := range fns {
			retType := cTypeToDataDream(fn.RetType.Raw)
			params := g.formatMDParams(fn.Params)

			// Signature
			sig := fmt.Sprintf("fn %s(%s)", fn.Name, params)
			if retType != "void" {
				sig += fmt.Sprintf(" -> %s", retType)
			}
			sb.WriteString(fmt.Sprintf("#### `%s`\n\n", fn.Name))
			sb.WriteString(fmt.Sprintf("```dd\n%s\n```\n\n", sig))

			// Description
			desc := fn.Comment
			if desc == "" {
				desc = generateDocComment(fn)
			}
			sb.WriteString(fmt.Sprintf("%s\n\n", desc))

			// Parameters table
			if len(fn.Params) > 0 {
				sb.WriteString("| Parameter | Type | Description |\n|-----------|------|-------------|\n")
				for _, p := range fn.Params {
					sb.WriteString(fmt.Sprintf("| `%s` | `%s` | |\n",
						sanitizeName(p.Name), cTypeToDataDream(p.Type.Raw)))
				}
				sb.WriteString("\n")
			}
		}
	}

	sb.WriteString("---\n\n")
	sb.WriteString("*Generated by `datadream bind` — DataDream compiler toolchain*\n")

	return sb.String()
}

func (g *DocGenerator) formatMDParams(params []CParam) string {
	if len(params) == 0 {
		return ""
	}
	parts := make([]string, len(params))
	for i, p := range params {
		parts[i] = fmt.Sprintf("%s: %s", sanitizeName(p.Name), cTypeToDataDream(p.Type.Raw))
	}
	return strings.Join(parts, ", ")
}
