package bindgen

import (
	"fmt"
	"path/filepath"
	"strings"
)

// ─── DataDream Wrapper Generator ──────────────────────────────────────────────

type WrapperGenerator struct {
	result    *ParseResult
	libName   string
}

func NewWrapperGenerator(result *ParseResult) *WrapperGenerator {
	return &WrapperGenerator{
		result:  result,
		libName: result.LibName,
	}
}

// Generate produces a complete .dd wrapper file
func (g *WrapperGenerator) Generate() string {
	var sb strings.Builder

	g.writeHeader(&sb)
	g.writeTypes(&sb)
	g.writeConstants(&sb)
	g.writeFunctions(&sb)

	return sb.String()
}

func (g *WrapperGenerator) writeHeader(sb *strings.Builder) {
	libTitle := capitalize(g.libName)
	headerFile := filepath.Base(g.result.HeaderFile)

	sb.WriteString(fmt.Sprintf(`// ╔══════════════════════════════════════════════════════════════════╗
// ║  DataDream bindings for: %s
// ║  Generated from: %s
// ║  Auto-generated by: datadream bind
// ║
// ║  Usage:
// ║    use %s;
// ║
// ╚══════════════════════════════════════════════════════════════════╝

`, libTitle, headerFile, g.libName))

	sb.WriteString(fmt.Sprintf("// Link the C library\n"))
	sb.WriteString(fmt.Sprintf("use c \"%s\";\n\n", headerFile))

	sb.WriteString(fmt.Sprintf("// ── %s Library ─────────────────────────────────────────────────\n\n", libTitle))
}

func (g *WrapperGenerator) writeTypes(sb *strings.Builder) {
	if len(g.result.Types) == 0 {
		return
	}
	sb.WriteString("// ═══ Types ═══════════════════════════════════════════════════════════\n\n")

	for _, t := range g.result.Types {
		switch t.Kind {
		case "struct":
			if t.Comment != "" {
				sb.WriteString(fmt.Sprintf("// %s\n", t.Comment))
			}
			sb.WriteString(fmt.Sprintf("struct %s {\n", t.Name))
			for _, f := range t.Fields {
				ddType := cTypeToDataDream(f.Type.Raw)
				sb.WriteString(fmt.Sprintf("    %s: %s;\n", f.Name, ddType))
			}
			sb.WriteString("}\n\n")
		case "enum":
			if t.Comment != "" {
				sb.WriteString(fmt.Sprintf("// %s\n", t.Comment))
			}
			sb.WriteString(fmt.Sprintf("enum %s {\n", t.Name))
			for _, v := range t.Values {
				name := stripEnumPrefix(v.Name, t.Name)
				if v.Value != "" {
					sb.WriteString(fmt.Sprintf("    %s; // = %s\n", name, v.Value))
				} else {
					sb.WriteString(fmt.Sprintf("    %s;\n", name))
				}
			}
			sb.WriteString("}\n\n")
		}
	}
}

func (g *WrapperGenerator) writeConstants(sb *strings.Builder) {
	if len(g.result.Defines) == 0 {
		return
	}
	sb.WriteString("// ═══ Constants ═══════════════════════════════════════════════════════\n\n")
	for _, d := range g.result.Defines {
		// Only include ones that look like simple values
		val := strings.TrimSpace(d.Value)
		if strings.Contains(val, "(") && !strings.HasPrefix(val, "(") {
			continue // skip macro functions
		}
		sb.WriteString(fmt.Sprintf("let %s = %s;\n", dataDreamConstName(d.Name), val))
	}
	sb.WriteString("\n")
}

func (g *WrapperGenerator) writeFunctions(sb *strings.Builder) {
	if len(g.result.Funcs) == 0 {
		return
	}

	sb.WriteString("// ═══ Functions ═══════════════════════════════════════════════════════\n\n")

	currentGroup := ""
	for _, fn := range g.result.Funcs {
		if fn.Group != currentGroup {
			currentGroup = fn.Group
			sb.WriteString(fmt.Sprintf("// ─── %s ─────────────────────────────────────────────────────\n\n", currentGroup))
		}

		// Doc comment
		if fn.Comment != "" {
			sb.WriteString(fmt.Sprintf("// %s\n", fn.Comment))
		} else {
			sb.WriteString(fmt.Sprintf("// %s\n", generateDocComment(fn)))
		}

		// Emit extern declaration
		retType := cTypeToDataDream(fn.RetType.Raw)
		if fn.IsVariadic {
			sb.WriteString(fmt.Sprintf("// Note: variadic function - use with care\n"))
		}

		params := g.formatDataDreamParams(fn.Params)
		if retType == "void" {
			sb.WriteString(fmt.Sprintf("extern fn %s(%s);\n\n", fn.Name, params))
		} else {
			sb.WriteString(fmt.Sprintf("extern fn %s(%s) -> %s;\n\n", fn.Name, params, retType))
		}

		// Generate a DataDream-style wrapper if the name can be improved
		friendly := friendlyName(fn.Name, g.libName)
		if friendly != fn.Name {
			sb.WriteString(fmt.Sprintf("// DataDream-style alias\n"))
			sb.WriteString(fmt.Sprintf("fn %s(%s)", friendly, params))
			if retType != "void" {
				sb.WriteString(fmt.Sprintf(" -> %s", retType))
			}
			sb.WriteString(" {\n")
			callArgs := g.callArgs(fn.Params)
			if retType != "void" {
				sb.WriteString(fmt.Sprintf("    return %s(%s);\n", fn.Name, callArgs))
			} else {
				sb.WriteString(fmt.Sprintf("    %s(%s);\n", fn.Name, callArgs))
			}
			sb.WriteString("}\n\n")
		}
	}
}

func (g *WrapperGenerator) formatDataDreamParams(params []CParam) string {
	if len(params) == 0 {
		return ""
	}
	parts := make([]string, len(params))
	for i, p := range params {
		ddType := cTypeToDataDream(p.Type.Raw)
		name := sanitizeName(p.Name)
		parts[i] = fmt.Sprintf("%s: %s", name, ddType)
	}
	return strings.Join(parts, ", ")
}

func (g *WrapperGenerator) callArgs(params []CParam) string {
	if len(params) == 0 {
		return ""
	}
	parts := make([]string, len(params))
	for i, p := range params {
		parts[i] = sanitizeName(p.Name)
	}
	return strings.Join(parts, ", ")
}

